### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by navierula** [SergeiEroshkin/intro-data-capstone-biodiversity#1]
**Presentation / Analysis Document (2/4)**
Great job analyzing your code in these slides. I liked how you made an observation of each output while citing the numbers. It might have been nice to include an objective of your analysis or explain the impact of your outputs. What suggestions would you make based on the data? Your slide should also include a proper introduction and conclusion.

**Code Accuracy (4/4)**
Your Python code is accurate for matplotlib plots, data analysis, and hypothesis testing. Accurate calculation of minimum detectable size, sample size determination in Foot & Mouth disease analysis was also included. Good job!

**Understanding Testing (4/4)**
You stated the hypothesis, ran hypothesis testing and stated the results, and interpreted your findings. Good job here!

**Comment by SergeiEroshkin** [comment]
thanks for the review Navraj.
